#+title: Tiles

I'll sort this out later.

* Colors
Each tile is represented by five colors:

- Background 1 (transparent usually)
- Background 2
- Base
- Accent
- Border

All of these are customized at runtime, not hardcoded.

You can set them either in tile definitions, or programatically at draw time.

These are color coded in the sprite with the following colors:
- Background 1: (255, 0, 255) (magenta)
- Background 2: (0, 255, 255) (cyan)
- Base: (255, 255, 255) (white)
- Accent: (255, 255, 0) (yellow)
- Border: set in shader.

The one gotcha is that the magenta color is automatically made transparent by MGCB - I'm disabling this.

* Orientations
For efficiency and convenience, the tilesets are arranges in the following way:

Each "block" tile that has autotiling capability is arranges in a row in the following order:
1. full "top" tile
2. Bottom single edge
3. Bottom left corner edge
4. bottom single edge and top single edge
5. bottom edge, left edge, and top edge
6. all edges

The tile is then rotated according the binary autotiling mask from some custom map logic. Thus, we can rotate obtain variations for the different edges and not have to manually draw every possible autotile. See DrawSystem.cs and TileSet.cs
